apiVersion: v1
kind: Pod
metadata:
  name: re2-elixir-benchmark
spec:
  containers:
  - name: re2-elixir-benchmark
    image: s22su/re2-elixir-benchmark:latest
    resources:
      requests:
        memory: 100Mi
        cpu: "0.1"
      limits:
        memory: 100Mi
        cpu: "1"
    command: ["./bin/r2_elixir_bench", "eval", "R2ElixirBench.Benchmark.call"]
